apiVersion: v1
kind: Namespace
metadata:
  name: ppp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pppbot
  namespace: ppp 
spec:
  selector:
    matchLabels:
      app: pppbot
  template:
    metadata:
      labels:
        app: pppbot
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: pppbot-container
        image: ghcr.io/poppyprograms/pppbot:fluxcd
        env:
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: pppsecrets
              key: DISCORD_TOKEN
        - name: GUILD_ID
          valueFrom:
            secretKeyRef:
              name: pppsecrets
              key: GUILD_ID
