name: Build the docker image
run-name: The bot is building the latest docker image by ${{github.actor}}
on:
  - push

jobs:
  deployment:
    runs-on: self-hosted
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract branch and lowercase repo
        id: vars
        run: |
          BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT

          REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "repo=$REPO" >> $GITHUB_OUTPUT

          TIMESTAMP=$(date +%s)
          echo "timestamp=$TIMESTAMP" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ steps.vars.outputs.repo }}:${{ steps.vars.outputs.branch }},ghcr.io/${{ steps.vars.outputs.repo }}:${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.timestamp }}
          build-args: |
            BOT_VERSION=${{ github.sha }}

      - name: Update the manifest
        run: |
          sed -i 's|image: ghcr.io/.*|image: ghcr.io/${{ steps.vars.outputs.repo }}:${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.timestamp }}|' ./clusters/k3d-maincluster/flux-system/deployment.yaml
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git commit -am "ci: bump version [skip ci]"
          git checkout -B ${{ steps.vars.outputs.branch }}-cd
          git push origin ${{ steps.vars.outputs.branch }}-cd
